[package]
name = "E0726_implicit_elided_lifetime_not_allowed_here"
version = "0.1.0"
edition = "2021"


[dependencies]
cursive = { version = "0.20", default-features = false, features = ["crossterm-backend"] }

